---
-   name: Pull the database
    community.docker.docker_image:
        name: "postgres:{{ database_postgres_version }}"
        source: pull
        force_source: no
        force_tag: yes
        tag: latest
        state: present
-   name: Create database data directory
    ansible.builtin.file:
        path: "{{ database_volume_path }}"
        state: directory
        owner: root
        group: root
        mode: 0777
    become: yes
-   name: Create Docker network
    community.docker.docker_network:
        name: "{{ docker_network_name }}"
        state: present
-   name: Start database container
    community.docker.docker_container:
        name: "{{ database_container_name }}"
        image: "postgres:17"
        hostname: "{{ database_container_hostname }}"
        state: started
        pull: never
        restart_policy: "unless-stopped"
        env:
            POSTGRES_DB: "{{ database_name }}"
            POSTGRES_USER: "{{ database_user }}"
            POSTGRES_PASSWORD: "{{ database_password }}"
        networks:
            -   name: "{{ docker_network_name }}"
        volumes:
            - "{{ database_volume_path }}:/var/lib/postgresql/data"

