[package]
name = "infrastructure"
edition = "2021"

[dependencies]
domain = { path = "../domain" }

async-trait = "0.1.87"
poise = "0.6.1"
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-native-tls", "postgres", "migrate"] }
