bot_container_name: "ssps-discord-bot"
bot_image: "ghcr.io/artifycz/ssps-discord-bot/ssps-discord-bot"
bot_container_hostname: "ssps-discord-bot"
public_network_name: "nginx"
bot_env_file: "/etc/ssps-discord-bot/.env"
discord_guild_id: "1019523857717133315"
docker_network_name: "ssps-discord-bot"
database_container_name: "ssps-discord-bot-db"
database_container_hostname: "ssps-discord-bot-db"
database_name: "ssps_discord_bot"
database_user: "ssps_discord_bot"
oauth_client_id: "89144b1a-dc0d-4306-9120-a4bc9c97c29e"
tenant_id: "354e4081-8121-4b0f-b318-c1bd2a901762"
authentication_callback_url: "https://ssps-bot.artify.zone/oauth/callback"
invite_link: "https://discord.com/invite/ePGN2XrkJU"
