name: Continuous Deployment
on:
    push:
        branches: [ "master" ]

concurrency:
    group: production
    cancel-in-progress: false

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production

