name: Continuous Delivery
on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to deploy to"
                required: true
                default: "production"
                type: environment

concurrency:
    group: '${{ github.event.inputs.environment }}'
    cancel-in-progress: false

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: '${{ github.event.inputs.environment }}'
        steps:
            -  uses: actions/checkout@v4
            -  name: Set SSH key
               run: |
                   mkdir -p ~/.ssh
                   echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
            -   name: Run playbook
                uses: dawidd6/action-ansible-playbook@v3
                with:
                    playbook: ansible/deploy.yaml
                    vault_password: ${{ secrets.VAULT_PASSWORD }}
                    options:
                        --inventory ansible/inventory/hosts.yaml
                        --extra-vars "bot_image_tag=sha-${{ github.sha }}"
                        --limit ${{ github.event.inputs.environment }}
