name: Continuous Integration

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    rust:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Run fmt
                run: cargo fmt -- --check
            -   name: Build
                run: cargo build --verbose
            -   name: Run tests
                run: cargo test --verbose
            -   name: Run Clippy
                run: cargo clippy -- -D warnings
